theme: jekyll-theme-hyde
title: Fast Robots
description: My name is Nidhi Sonwalkar, and I am a first-semester senior studying mechanical engineering. This page will contain my work in the Spring 2024 Fast Robots class.
